name: YAML to Table
on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Print current directory
        run: echo $PWD

      - name: Convert YAML to Table
        run: |
          npm install yamljs
          node -e "const fs = require('fs'); const yaml = require('yamljs'); const data = yaml.load(fs.readFileSync('input.yml', 'utf8')); const table = Object.entries(data).map(([key, value]) => \`| \${key} | \${value} |\`).join('\n'); fs.writeFileSync('output.txt', table);"
