name: Convert YAML to Table
on:
  push:
    branches:
      - main

jobs:
  convert-to-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert YAML to Table
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');

            const fileContent = fs.readFileSync('input.yml', 'utf8');
            const data = yaml.safeLoad(fileContent);

            const tableData = Object.entries(data).map(([key, value]) => [key, value]);

            console.log(table(tableData, { align: ['l', 'l'] }));
