name: Convert YAML to Table
on:
  push:
    branches:
      - main

jobs:
  convert-to-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install js-yaml table

      - name: Convert YAML to Table
        run: |
          const fs = require('fs');
          const yaml = require('js-yaml');
          const { table } = require('table');

          const fileContent = fs.readFileSync('input.yaml', 'utf8');
          const data = yaml.safeLoad(fileContent);

          const tableData = Object.entries(data).map(([key, value]) => [key, value]);

          console.log(table(tableData, { align: ['l', 'l'] }));
